### ISSUE TITLE
geom_beeswarm method = "center" doesn't seem to be working properly

### ISSUE THREAD

**Issue by Ari04T** [csdaw/ggbeeswarm2#2]
When I try to use `geom_beeswarm(method = "center")`, the plot doesn't seem to be doing what the documentation of `beeswarm` says it does. As you can see, the points are not centered.

```R
set.seed(123)
distro <- list(runif = runif(100, min = -3, max = 3), 
               rnorm = rnorm(100))

distro2 %>% 
    ggplot(aes(y = rev(variable), x = value)) + 
    ggbeeswarm2::geom_beeswarm(method = "center", side = -1L)

distro2 %>% 
    ggplot(aes(x = rev(variable), y = value)) + 
    geom_beeswarm(method = "center")
```

![image](https://user-images.githubusercontent.com/7259598/117888591-4cdc5c00-b280-11eb-9aa8-7230daf75ca6.png)

If I try the following with `method = "square"` it seems to work just fine.
```R
distro2 %>% 
    ggplot(aes(x = rev(variable), y = value)) + 
    geom_beeswarm(method = "square")
```
![image](https://user-images.githubusercontent.com/7259598/117888681-6aa9c100-b280-11eb-8b51-d3504b3451c6.png)

**Comment by csdaw** [comment]
Hi @Ari04T,

Thanks for raising this. It wasn't working because I forgot to account for the US spelling of centre/center. This should be fixed now. Also just to note, eventually the changes made in this fork will be incorporated into the actual `ggbeeswarm` package and this fork will be abandoned.


``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)

set.seed(123)
distro <- list(runif = runif(100, min = -3, max = 3), 
               rnorm = rnorm(100))

distro2 <- as.data.frame(rev(distro)) %>% 
  tidyr::pivot_longer(
    everything(), 
    values_to = "value", 
    names_to = "variable"
  )

distro2 %>% 
  ggplot(aes(x = rev(variable), y = value)) + 
  ggbeeswarm2::geom_beeswarm(method = "center", spacing = 0.8)
```

![](https://i.imgur.com/3bTNBlS.png)

``` r
distro2 %>% 
  ggplot(aes(x = rev(variable), y = value)) + 
  ggbeeswarm2::geom_beeswarm(method = "centre", spacing = 0.8)
```

![](https://i.imgur.com/vAq0Isf.png)

<sup>Created on 2021-07-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
